// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tboxibhkqcnefnssyzar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRib3hpYmhrcWNuZWZuc3N5emFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTkyMTUsImV4cCI6MjA1ODc5NTIxNX0.uTyUROYAo5BMvvInlnUl0_C0JxU2_LfnNvO4HKEjVWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);